services:
  - type: web
    name: roommate-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run roomAI_app.py --server.port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
